# Generated by Django 2.1.5 on 2020-04-13 11:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200411_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(default='write blog content'),
        ),
    ]
