# Generated by Django 2.1.5 on 2020-04-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200415_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='comment_count',
        ),
    ]
