# Generated by Django 2.1.5 on 2020-04-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogpost_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='blog.BlogPost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='blog.BlogPost'),
        ),
    ]
